version: "3"
services:
  nginx:
    container_name: workspace_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "80:80"
    networks:
      - internal
    volumes:
      - ../:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    container_name: workspace_php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ../:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    container_name: workspace_mysql
    build:
      context: .
      dockerfile: mysql/Dockerfile
    command: --sql_mode=""
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - ./mysql/data:/var/lib/mysql
networks:
  internal:
    driver: bridge
